openapi: 3.0.3
info:
  title: 'Prince Hardware API'
  description: 'API for Prince Hardware Store customer registration for reward cards'
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/auth/login:
    post:
      summary: Login
      operationId: login
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Authentication Controller'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: chanel14@example.org
                password:
                  type: string
                  description: ''
                  example: '/O^Fy54-b/9K.D]!'
              required:
                - email
                - password
      security: []
  /api/auth/register:
    post:
      summary: Register
      operationId: register
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Authentication Controller'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: rwniyqt
                date_of_birth:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-12-08T22:01:49'
                address:
                  type: string
                  description: ''
                  example: officiis
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: mgibson@example.com
                phone_number:
                  type: string
                  description: ''
                  example: "'+63-910-123-4567'\nd"
                signature:
                  type: string
                  format: binary
                  description: 'Must be an image.'
              required:
                - full_name
                - date_of_birth
                - address
                - email
                - phone_number
                - signature
      security: []
  /api/auth/refresh:
    post:
      summary: 'Refresh Token'
      operationId: refreshToken
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Authentication Controller'
  /api/auth/logout:
    delete:
      summary: Logout
      operationId: logout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Authentication Controller'
  /sanctum/csrf-cookie:
    get:
      summary: 'Return an empty response simply to trigger the storage of the CSRF cookie in the browser.'
      operationId: returnAnEmptyResponseSimplyToTriggerTheStorageOfTheCSRFCookieInTheBrowser
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Endpoints
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
tags:
  -
    name: 'Authentication Controller'
    description: ''
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
